site_name: Transformer

theme:
  name: material

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src]  # search packages in the src folder

nav:
  - Installation: index.md
  - Introduction: introduction.md
  - Reference: 
    - Positional Encoding: src/positional_encoding.md
    - Embedding: src/embedding.md
